### ISSUE TITLE
[HELP] BfNativeHook

### ISSUE THREAD

**Issue by martiano9** [Deathmax/BraveFrontier#1]
@cheahjs , I try to attach BfNativeHook to CreateRemoteThread but could not get it running. Can you give me a hint on how to get it running? I also try to attach the dll directly to BF.Windows.exe but also could not get result on debug output.

**Comment by cheahjs** [comment]
It's been a while since I used it, but you need to setup the DLL in a very specific way. See this stackoverflow answer on what to do: https://reverseengineering.stackexchange.com/questions/17127/how-to-reverse-engineer-a-windows-10-uwp-app/17200#17200

No further support will be given, as this project is no longer maintained.
